### ISSUE TITLE
JSX namespace should be scoped to the factory function

### ISSUE THREAD

**Issue by jcfranco** [AFASSoftware/maquette-jsx#1]
It'd be nice to move the [global JSX typings](https://github.com/AFASSoftware/maquette-jsx/blob/master/src/index.ts#L6-L11) to a local namespace since TypeScript 2.8 now resolves JSX via the factory function. This is also recommended in their [release notes](https://blogs.msdn.microsoft.com/typescript/2018/03/27/announcing-typescript-2-8/#jsx-namespace-resolution):

> Going forward, we recommend that new JSX-oriented libraries avoid placing JSX in the global scope, and instead export it from the same location as the respective factory function.

**Comment by jcfranco** [comment]
FWIW, the following works if you explicitly import the factory function, but breaks the `enableGlobaJsx` approach:

```ts
import { VNode, VNodeChild, VNodeProperties } from 'maquette';

declare global  {
    function jsx(tagName: string, properties: VNodeProperties | null, ...children: (VNode | string)[]): VNode;
}

export declare namespace jsx {
  namespace JSX {
    interface IntrinsicElements {
      [tagName: string]: VNodeProperties;
    }
    type Element = VNode;
  }
}

export declare let jsx: (tagName: string, properties: VNodeProperties | null, ...childNodes: VNodeChild[]) => VNode;

export declare let enableGlobalJsx: () => void;
```

**Comment by johan-gorter** [comment]
I do not see how your suggestion would break the enableGlobalJsx approach. Javascript users would not be affected and Typescript users would need to update to the latest Typescript version and not call enableGlobalJsx anymore right?

**Comment by johan-gorter** [comment]
sorry about the late reply btw

**Comment by jcfranco** [comment]
> Typescript users would need to update to the latest Typescript version and not call enableGlobalJsx anymore right?

And explicitly import the JSX factory, even if it's not used. Otherwise, TS complains since the JSX typings aren't on the global namespace anymore:

```tsx
import { MaquetteComponent } from 'maquette';

// this import is now required, otherwise: 
// TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
import { jsx } from "maquette-jsx";

export interface TextInputConfig {
  placeholder: string;
  getValue: () => string;
  setValue: (value: string) => void;
}

export let createTextInput = (config: TextInputConfig) : MaquetteComponent => {
  
  function handleInput(evt: Event) {
    config.setValue((evt.target as HTMLInputElement).value)
  }
  
  return {
    render: () => {
      return <input 
        type="text" 
        placeholder={config.placeholder}
        value={config.getValue()} 
        oninput={handleInput} />;
    }
  }
};
```

If the import isn't a deal-breaker, then my suggestion works fine. 😄

**Comment by johan-gorter** [comment]
Having an unused import will cause trouble in combination with tslint and editors doing 'organize imports'. A function `enableLocalJsx` next to `enableGlobalJsx` which does a noop can fix this. What do you think?

**Comment by jcfranco** [comment]
> Having an unused import will cause trouble in combination with tslint and editors doing 'organize imports'

I can't speak from the Babel-side of things, but at least from the TypeScript perspective, it knows what the JSX factory is (via `--jsxFactory`) and therefore that it's used.

FWIW, I've had no issues w/ VSCode, IntelliJ nor TSLint.

**Comment by johan-gorter** [comment]
@jcfranco I created a pre-release version, maquette-jsx@2.1.2-0 can you try this out if this is what you mean?

**Comment by jcfranco** [comment]
Thanks. Tested on `maquette-typescript-jsx-starter` and it works like a charm. I've submitted a [PR](https://github.com/AFASSoftware/maquette-typescript-jsx-starter/pull/2).

**Comment by johan-gorter** [comment]
Nice, I created an official 3.0.0 release. Typescript <2.8 users should remain on a 2.x version

**Comment by jcfranco** [comment]
Thanks again!
